apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-stable
spec:
  selector:
    matchLabels:
      app: appfront
  template:
    metadata:
      labels:
        app: appfront
        version: {{ .Values.stableVersionStaticFiles }}
    spec:
      containers:
      - name: next-front
        image: 300150/next-front:v42
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_STATIC_VERSION
          value: stable
        - name: NEXT_PUBLIC_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name