apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-k3s
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: http2
      hosts:
      - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-appfront
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway-k3s
  http:
    - route:
        - destination:
            host: front-service

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-appfront
spec:
  host: front-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-user-session
  subsets:
    - name: v1
      labels: 
        version: A
    - name: v2
      labels:
        version: B