apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appfront
  template:
    metadata:
      labels:
        app: appfront
        version: canary
    spec:
      containers:
      - name: next-front
        image: 300150/next-front:v51
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_STATIC_VERSION
          value: canary
        - name: NEXT_PUBLIC_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
