apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-appfront
spec:
  host: front-service
  subsets:
  - name: v1
    labels:
      version: canary
  - name: v2
    labels:
      version: stable