apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-appfront
spec:
  host: front-service.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: 1.0.0
  - name: v2
    labels:
      version: 2.0.0