apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-appfront
  namespace: default
spec:
  hosts:
  - front-service.default.svc.cluster.local
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: /1.0.0/
      port: 80
    route:
    - destination:
        host: front-service.default.svc.cluster.local
        subset: v1
        port:
          number: 80
  - match:
    - uri:
        prefix: /2.0.0/
      port: 80
    route:
    - destination:
        host: front-service.default.svc.cluster.local
        subset: v2
        port:
          number: 80
  - route:
    - destination:
        host: front-service.default.svc.cluster.local
        port:
          number: 80