apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-appfront
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway-k3s
  http:
  - match:
    - uri:
        prefix: /canary/
    route:
    - destination:
        host: front-service
        subset: v1
  - match:
    - uri:
        prefix: /stable/
    route:
    - destination:
        host: front-service
        subset: v2